# vim:fileencoding=utf-8:ft=conf:foldmethod=marker
# vim:ft=kitty

# : Terminal {{{
shell_integration   disabled
#: }}}

# : Fonts {{{
font_family                 PragmataPro Mono Liga Regular
bold_font                   PragmataPro Mono Liga Bold
italic_font                 PragmataPro Mono Liga Italic
bold_italic_font            PragmataPro Mono Liga Bold Italic
font_size                   16
text_composition_strategy   1.8

# font_family                 SF Mono Regular
# bold_font                   SF Mono Semibold
# italic_font                 SF Mono Regular Italic
# bold_italic_font            SF Mono Semibold Italic
# font_size                   15
# text_composition_strategy   2.3

adjust_line_height    1

narrow_symbols U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0C8,U+E0CA,U+E0CC-U+E0D2,U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E634,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF

#: }}}

#: Performance tuning {{{
repaint_delay 1
input_delay 1
sync_to_monitor yes
#: }}}

#: Window layout {{{
window_padding_width 40
hide_window_decorations no
#: }}}

#: Clipboard {{{
map kitty_mod+c  copy_to_clipboard
map cmd+c        copy_to_clipboard
map kitty_mod+v  paste_from_clipboard
map cmd+v        paste_from_clipboard
map kitty_mod+s  paste_from_selection
map shift+insert paste_from_selection
map kitty_mod+o  pass_selection_to_program
#: }}}

#: Font sizes {{{
map cmd+equal           change_font_size all +2.0
map cmd+minus           change_font_size all -2.0
#: }}}

#: Miscellaneous {{{
map kitty_mod+enter    toggle_fullscreen
#: }}}

# BEGIN_KITTY_THEME
# Kanso Zen
include current-theme.conf
# END_KITTY_THEME

# OS Window titlebar colors
# wayland_titlebar_color system
# macos_titlebar_color #1E222A

tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
